# Generated by Django 4.1.2 on 2023-02-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionagence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('siege', models.CharField(default='Yaounde', max_length=30)),
                ('telephone', models.CharField(default='678963685', max_length=30)),
                ('description', models.CharField(default='Description de l agence ', max_length=30)),
            ],
        ),
    ]
