# Generated by Django 4.1.2 on 2023-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionagence',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
