# Generated by Django 4.1.2 on 2023-04-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationcreate',
            name='user',
        ),
    ]
