# Generated by Django 4.1.2 on 2023-04-27 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_reservation', '0002_remove_reservationcreate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcreate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
