# Generated by Django 4.1.2 on 2023-05-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_admin', '0002_gestionagence_published'),
        ('gestion_reservation', '0003_reservationcreate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcreate',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_admin.gestionagence'),
        ),
    ]
