# Generated by Django 4.1.2 on 2023-04-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_authentification', '0002_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
